# Autogenerated wrapper script for fplll_jll for x86_64-apple-darwin14
export fplll, latticegen, latsieve, libfplll

using CompilerSupportLibraries_jll
using GMP_jll
using MPFR_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "DYLD_FALLBACK_LIBRARY_PATH"

# Relative path to `fplll`
const fplll_splitpath = ["bin", "fplll"]

# This will be filled out by __init__() for all products, as it must be done at runtime
fplll_path = ""

# fplll-specific global declaration
function fplll(f::Function; adjust_PATH::Bool = true, adjust_LIBPATH::Bool = true)
    global PATH, LIBPATH
    env_mapping = Dict{String,String}()
    if adjust_PATH
        if !isempty(get(ENV, "PATH", ""))
            env_mapping["PATH"] = string(PATH, ':', ENV["PATH"])
        else
            env_mapping["PATH"] = PATH
        end
    end
    if adjust_LIBPATH
        if !isempty(get(ENV, LIBPATH_env, ""))
            env_mapping[LIBPATH_env] = string(LIBPATH, ':', ENV[LIBPATH_env])
        else
            env_mapping[LIBPATH_env] = LIBPATH
        end
    end
    withenv(env_mapping...) do
        f(fplll_path)
    end
end


# Relative path to `latticegen`
const latticegen_splitpath = ["bin", "latticegen"]

# This will be filled out by __init__() for all products, as it must be done at runtime
latticegen_path = ""

# latticegen-specific global declaration
function latticegen(f::Function; adjust_PATH::Bool = true, adjust_LIBPATH::Bool = true)
    global PATH, LIBPATH
    env_mapping = Dict{String,String}()
    if adjust_PATH
        if !isempty(get(ENV, "PATH", ""))
            env_mapping["PATH"] = string(PATH, ':', ENV["PATH"])
        else
            env_mapping["PATH"] = PATH
        end
    end
    if adjust_LIBPATH
        if !isempty(get(ENV, LIBPATH_env, ""))
            env_mapping[LIBPATH_env] = string(LIBPATH, ':', ENV[LIBPATH_env])
        else
            env_mapping[LIBPATH_env] = LIBPATH
        end
    end
    withenv(env_mapping...) do
        f(latticegen_path)
    end
end


# Relative path to `latsieve`
const latsieve_splitpath = ["bin", "latsieve"]

# This will be filled out by __init__() for all products, as it must be done at runtime
latsieve_path = ""

# latsieve-specific global declaration
function latsieve(f::Function; adjust_PATH::Bool = true, adjust_LIBPATH::Bool = true)
    global PATH, LIBPATH
    env_mapping = Dict{String,String}()
    if adjust_PATH
        if !isempty(get(ENV, "PATH", ""))
            env_mapping["PATH"] = string(PATH, ':', ENV["PATH"])
        else
            env_mapping["PATH"] = PATH
        end
    end
    if adjust_LIBPATH
        if !isempty(get(ENV, LIBPATH_env, ""))
            env_mapping[LIBPATH_env] = string(LIBPATH, ':', ENV[LIBPATH_env])
        else
            env_mapping[LIBPATH_env] = LIBPATH
        end
    end
    withenv(env_mapping...) do
        f(latsieve_path)
    end
end


# Relative path to `libfplll`
const libfplll_splitpath = ["lib", "libfplll.6.dylib"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libfplll_path = ""

# libfplll-specific global declaration
# This will be filled out by __init__()
libfplll_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libfplll = "@rpath/libfplll.6.dylib"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"fplll")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    # We first need to add to LIBPATH_list the libraries provided by Julia
    append!(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)])
    # From the list of our dependencies, generate a tuple of all the PATH and LIBPATH lists,
    # then append them to our own.
    foreach(p -> append!(PATH_list, p), (CompilerSupportLibraries_jll.PATH_list, GMP_jll.PATH_list, MPFR_jll.PATH_list,))
    foreach(p -> append!(LIBPATH_list, p), (CompilerSupportLibraries_jll.LIBPATH_list, GMP_jll.LIBPATH_list, MPFR_jll.LIBPATH_list,))

    global fplll_path = normpath(joinpath(artifact_dir, fplll_splitpath...))

    push!(PATH_list, dirname(fplll_path))
    global latticegen_path = normpath(joinpath(artifact_dir, latticegen_splitpath...))

    push!(PATH_list, dirname(latticegen_path))
    global latsieve_path = normpath(joinpath(artifact_dir, latsieve_splitpath...))

    push!(PATH_list, dirname(latsieve_path))
    global libfplll_path = normpath(joinpath(artifact_dir, libfplll_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libfplll_handle = dlopen(libfplll_path)
    push!(LIBPATH_list, dirname(libfplll_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(LIBPATH_list, ':')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

